### PR TITLE
Changing Launch Date

### PR DESCRIPTION
**Pull request by matthewlee626**
You might already have this in the works, but this might be a good placeholder text for launch date for now.

### CODE REVIEW

**Comment by sampoder** [comment]
Thank you so much! I'll merge this!!!

**Comment by matthewlee626** [comment]
I don't think the changes are rendered on the actual website. Did I do something wrong?

**Comment by sampoder** [comment]
weird lemme look into it

**Comment by sampoder** [comment]
Netlify messed up, rebuilding now

**Comment by sampoder** [comment]
should be fixed now

**Comment by matthewlee626** [comment]
Nice, sounds good!

**Comment by sampoder** [comment]
thanks again

-- 
This email and any attachments are confidential and may also be privileged. 
If you have received this message in error, please (a) notify the sender 
immediately, (b) destroy this email and any attachments, and (c) do not 
use, copy, store and/or disclose to any person this email and any 
attachments. The sender gives no representation or guarantee with respect 
to the integrity of any emails or attached files and the recipient should 
check the integrity of and scan this email and any attached files for 
viruses prior to opening.

**Pull request merged**
